/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Security by Design – Theory of Everything",
  "tagline": "Framework prática e aberta para desenvolver software seguro",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://shiftleftpt.github.io",
  "baseUrl": "/sbd-theory-of-everything/",
  "organizationName": "shiftleftpt",
  "projectName": "sbd-theory-of-everything",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "pt",
    "locales": [
      "pt"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "sbd-toe",
        "path": "docs/sbd-toe",
        "routeBasePath": "sbd-toe",
        "sidebarPath": "/Users/pedrofarinha/Projects/sbd-toe/sbd-theory-of-everything/manuals_src/sidebars-sbd-toe.ts"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ia",
        "path": "docs/ia",
        "routeBasePath": "ia"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "supply-chain",
        "path": "docs/supply-chain",
        "routeBasePath": "supply-chain"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ameacas",
        "path": "docs/ameacas",
        "routeBasePath": "ameacas"
      }
    ],
    [
      "@docusaurus/plugin-content-pages",
      {
        "path": "src/pages"
      }
    ]
  ],
  "themes": [
    [
      "@docusaurus/theme-classic",
      {
        "customCss": "./src/css/custom.css"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "mermaid": {
      "theme": {
        "light": "default",
        "dark": "dark"
      }
    },
    "navbar": {
      "title": "Security by Design – Theory of Everything",
      "logo": {
        "alt": "Security by Design – Theory of Everything",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "sbdToeSidebar",
          "docsPluginId": "sbd-toe",
          "docId": "intro",
          "position": "left",
          "label": "SbD-ToE"
        },
        {
          "type": "docSidebar",
          "sidebarId": "defaultSidebar",
          "docsPluginId": "ia",
          "docId": "intro",
          "position": "left",
          "label": "IA"
        },
        {
          "type": "docSidebar",
          "sidebarId": "defaultSidebar",
          "docsPluginId": "supply-chain",
          "docId": "intro",
          "position": "left",
          "label": "Supply Chain"
        },
        {
          "type": "docSidebar",
          "sidebarId": "defaultSidebar",
          "docsPluginId": "ameacas",
          "docId": "intro",
          "position": "left",
          "label": "Ameaças"
        },
        {
          "to": "/licenciamento",
          "label": "Licença",
          "position": "right"
        },
        {
          "to": "/about",
          "label": "Sobre",
          "position": "right"
        },
        {
          "href": "https://github.com/Shiftleftpt/sbd-theory-of-everything",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Manuais",
          "items": [
            {
              "label": "SbD-ToE",
              "to": "/sbd-toe/intro"
            },
            {
              "label": "IA",
              "to": "/ia/intro"
            },
            {
              "label": "Supply Chain",
              "to": "/supply-chain/intro"
            },
            {
              "label": "Ameaças",
              "to": "/ameacas/intro"
            }
          ]
        },
        {
          "title": "Mais",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Shiftleft - Secure Software Engineering, Lda. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "presets": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
