import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sbdToeSidebar: [
    'index',
    'como-usar-este-manual',
    {
      type: 'category',
      label: 'Capítulos Técnicos',
      items: [
        {
          type: 'category',
          label: '1-Classificaçao das Aplicações',
          link: { type: 'doc', id: 'classificacao-aplicacoes/intro' },
          items: [
            'classificacao-aplicacoes/aplicacao-lifecycle',
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '01-classificacao-aplicacoes/addon' }],
            }
          ],
        }
        ,
        {
          type: 'category',
          label: '2-Requisitos de Segurança',
          link: { type: 'doc', id: 'requisitos-seguranca/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '02-requisitos-seguranca/addon' }],
            },
            'requisitos-seguranca/aplicacao-lifecycle',
          ],
        }, 
        {
          type: 'category',
          label: '3-Threat Modeling',
          link: { type: 'doc', id: 'threat-modeling/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '03-threat-modeling/addon' }],
            },
            'threat-modeling/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '4-Arquitetura Segura',
          link: { type: 'doc', id: 'arquitetura-segura/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '04-arquitetura-segura/addon' }],
            },
            'arquitetura-segura/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '5-Controlo de Dependências (SBOM, SCA)',
          link: { type: 'doc', id: 'dependencias-sbom-sca/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '05-dependencias-sbom-sca/addon' }],
            },
            'dependencias-sbom-sca/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '6-Desenvolvimento Seguro',
          link: { type: 'doc', id: 'desenvolvimento-seguro/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '06-desenvolvimento-seguro/addon' }],
            },
            'desenvolvimento-seguro/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '7-CI/CD Seguro',
          link: { type: 'doc', id: 'cicd-seguro/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '07-cicd-seguro/addon' }],
            },
            'cicd-seguro/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '8-Infrastructure as Code (IaC)',
          link: { type: 'doc', id: 'iac-infraestrutura/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '08-iac-infraestrutura/addon' }],
            },
            'iac-infraestrutura/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '9-Containers e Imagens',
          link: { type: 'doc', id: 'containers-imagens/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '09-containers-imagens/addon' }],
            },
            'containers-imagens/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '10-Testes de Segurança',
          link: { type: 'doc', id: 'testes-seguranca/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '10-testes-seguranca/addon' }],
            },
            'testes-seguranca/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '11-Deploy Seguro',
          link: { type: 'doc', id: 'deploy-seguro/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '11-deploy-seguro/addon' }],
            },
            'deploy-seguro/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '12-Monitorização e Operações',
          link: { type: 'doc', id: 'monitorizacao-operacoes/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '12-monitorizacao-operacoes/addon' }],
            },
            'monitorizacao-operacoes/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '13-Formação e Onboarding',
          link: { type: 'doc', id: 'formacao-onboarding/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '13-formacao-onboarding/addon' }],
            },
            'formacao-onboarding/canon/aplicacao-lifecycle',
          ],
        },
        {
          type: 'category',
          label: '14-Governança e Contratação',
          link: { type: 'doc', id: 'governanca-contratacao/intro' },
          items: [
            {
              type: 'category',
              label: '📚 Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '14-governanca-contratacao/addon' }],
            },
            'governanca-contratacao/canon/aplicacao-lifecycle',
          ],
        }
      ]
    },
    {
      type: 'category',
      label: 'Matriz de Alinhamento',
      items: [
        'capitulos-basilares',
        'matriz-frameworks',
        'coverage-frameworks',
        'gaps-por-framework',
      ],
    },
  ],
};

export default sidebars;
